### PR TITLE
Support Multitask in mmseg

### PR DESCRIPTION
**Pull request by echonax07**
Hello everyone,
I am adding all of you as reviewers so that everyone can understand how we will be modifying the code, creating pull requests, and conducting code reviews.

The template for creating PR was already given by the mmseg developer; I just modified parts of it 😄 .

## Motivation

To enable multitask learning in segmentation
## Modification

Changes have been made in Dataset, model, Metric and Custom hooks.

A detailed description of all the changes is available at https://github.com/Fernando961226/sea-ice-mmseg/blob/mmseg_multitask/docs_ai4arctic/multitask_readme.md

Also, https://github.com/astokholm/AI4ArcticSeaIceChallenge repo has been added as a folder called AI4ArcticSeaIceChallenge.

## Use cases 

The template config file to be used can be found here: [configs/multi_task_ai4arctic/mae_ai4arctic_ds5_pt_80_ft_20.py](https://github.com/Fernando961226/sea-ice-mmseg/blob/mmseg_multitask/configs/multi_task_ai4arctic/mae_ai4arctic_ds5_pt_80_ft_20.py)
## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMDet3D.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by Fernando961226 — APPROVED** [review]
Is there any reason why we need AI4ArticSeaIceChallenge folder? Does not seem like we need all the files there 

I think we can move  convert_raw_icechart.py, create_data_splits.py, utils.py, save_SIC_SOD_FLOE and whatever else is needed into tools/AI4Artic_dataset

Why changes to demo/image_demo.py

**Comment by echonax07** [comment]
I added AI4ArticSeaIceChallenge as a folder is because it helps differentiate between original and mmseg files. Also the AI4ArticSeaIceChallenge folder is only 4MB.

Changes to demo/image_demo.py is done so that the result is saved. By default save_dir is none, so earlier no file was saved. Reference: https://github.com/Fernando961226/sea-ice-mmseg/blob/f3ba98a493fde6e69be2f43649037e92f9f90d05/mmseg/apis/inference.py#L152

**Comment by Fernando961226** [comment]
@echonax07 That make sense, however we add additional files to the repo that do nothing it will just make it more confusing for some comming in.

**Comment by echonax07** [comment]
@Fernando961226 True; in that case, feel free to delete any unnecessary files as you are writing a new data loader.

**Comment by Fernando961226** [comment]
Okay in that case let's just merge and we can delete them later once the dataloader is completed!

**Pull request merged**
